project_id = "jnszyfzletlalgvqbcfs"

[functions.verify-face]
verify_jwt = false

[functions.get-face-data]
verify_jwt = false

[functions.create-student-account]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.log-login]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.analyze-chat-importance]
verify_jwt = false

[functions.initiate-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false